// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ-piFuIZowu8d5cQR6fA3mGA4pBUMsNs',
    appId: '1:947461782925:web:2c8676c12eed38c88891c4',
    messagingSenderId: '947461782925',
    projectId: 'isibappsmoodle',
    authDomain: 'isibappsmoodle.firebaseapp.com',
    databaseURL: 'https://isibappsmoodle-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isibappsmoodle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDHYj3Hc1Y1MZKTGJ41n9EXMrzQQdFkY',
    appId: '1:947461782925:android:765f8f3233629bec8891c4',
    messagingSenderId: '947461782925',
    projectId: 'isibappsmoodle',
    databaseURL: 'https://isibappsmoodle-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isibappsmoodle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmLsFuuB9l3v-TE4GAjtDOgZ9fRuV5sIE',
    appId: '1:947461782925:ios:e81e2bb8c528e8238891c4',
    messagingSenderId: '947461782925',
    projectId: 'isibappsmoodle',
    databaseURL: 'https://isibappsmoodle-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isibappsmoodle.firebasestorage.app',
    iosBundleId: 'com.example.isibappmoodle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmLsFuuB9l3v-TE4GAjtDOgZ9fRuV5sIE',
    appId: '1:947461782925:ios:e81e2bb8c528e8238891c4',
    messagingSenderId: '947461782925',
    projectId: 'isibappsmoodle',
    databaseURL: 'https://isibappsmoodle-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isibappsmoodle.firebasestorage.app',
    iosBundleId: 'com.example.isibappmoodle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ-piFuIZowu8d5cQR6fA3mGA4pBUMsNs',
    appId: '1:947461782925:web:80ae57d33eece33c8891c4',
    messagingSenderId: '947461782925',
    projectId: 'isibappsmoodle',
    authDomain: 'isibappsmoodle.firebaseapp.com',
    databaseURL: 'https://isibappsmoodle-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isibappsmoodle.firebasestorage.app',
  );
}
